# Generated by Django 4.0.6 on 2022-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
